added check for noclassdeffounderror that catches sitation when user has renamed an event filter to fix the character case, for example. before this threw an error (not an exception) if the filter had been loaded previously and now could not be found. Now the filter is just removed from the filter list, which is the correct operation.
git-svn-id: svn://svn.code.sf.net/p/jaer/code@4797 b7f4320f-462c-0410-a916-d9f35bb82d52